toggle_hud=F10

### --- APARIENCIA ---
legacy_layout=0
horizontal=0
font_size=24
background_alpha=0.4
position=top-left
round_corners=10

### --- TARJETA GRÁFICA (GPU) ---
gpu_stats
gpu_temp
gpu_power      # <--- ¡ESTE ACTIVA EL CONSUMO DE ENERGÍA EN WATTS!
gpu_load
gpu_clock
gpu_mem_clock
vram

### --- PROCESADOR (CPU) ---
cpu_stats
cpu_temp
cpu_power
cpu_load
cpu_clock
ram

### --- RENDIMIENTO (FPS) ---
fps
frametime
frame_timing=1

### --- EXTRAS ---
engine_version
gpu_name
vulkan_driver
time