monitor.alsa.rules = [
  {
    matches = [
      {
        -- Esto aplica a todas las fuentes de audio (micrófonos)
        node.name = "~alsa_input.*"
      }
    ],
    actions = {
      update-props = {
        -- Evita que PulseAudio/PipeWire cambie el volumen por software
        ["channelmix.upmix"] = false,
        ["session.suspend-on-idle"] = false,
        -- Bloquea el volumen para que no sea manipulado externamente
        ["node.pause-on-idle"]      = false,
      }
    }
  }
]